language: python

python:
  - 3.3

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
  - pip install --use-mirrors -r requirements.txt -r requirements-development.txt

script:
  - py.test --cov g4s
