language: python

python:
  - 3.3

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
  - pip install -r requirements.txt

script:
  - py.test --cov g4s
  - ./build-api-doc.sh
