language: python

install:
  - pip install detox

script:
  - detox -e py33 -e flake8

after_success:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
  - source ~/virtualenv/python3.3/bin/activate
  - pip install coveralls coviolations-app coverage pep8 pip-tools
  - coveralls
  - covio
